apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-operator-deployment-acc
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: gitops-operator-deployment
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps", "extensions"]
    resources: ["deployments", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: gitops-operator-deployment
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-operator-deployment
subjects:
- kind: ServiceAccount
  name: gitops-operator-deployment-acc
  namespace: default
